---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-config
data:
  WORDPRESS_DB_HOST: "mysql.wp.svc.cluster.local:3306"
  WORDPRESS_DB_NAME: wpdb
  WORDPRESS_DB_USER: root
---
apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
type: Opaque
data:
  WORDPRESS_DB_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: v1
kind: Pod
metadata:
  name: wordpress-deploy
  labels:
    name: wordpress-deploy
    customer-id: "1"
spec:
  containers:
  - name: wordpress
    image: wordpress
    envFrom:
      - secretRef:
          name: wp-secret
      - configMapRef:
          name: wp-config
    resources:
      limits:
        memory: "1024Mi"
        cpu: "1000m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wp-svc
spec:
  type: ClusterIP
  selector:
    name: wp-deploy
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wp-ing
  labels:
    name: wp-ing
    customer-id: "1"
spec:
  ingressClassName: nginx
  rules:
  - host: wp-1-139.59.217.220.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: wp-svc
            port: 
              number: 80
---
